### ISSUE TITLE
Create common components

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#7]
## Motivation

In order to have fully working frontend project we'll need couple of common components that will ease the development.

This issue is used to track the progress on their individual development cycle.

https://ora.pm/project/277933/task/4495226

## Components

- [x] `AppBar` (#38, thanks to @kachar)
- [x] `Footer` (#12, thanks to @ani-kalpachka)
- [x] `Nav`
- [x] `MobileNav`
  > Responsive layout of the navigation menu
- [x] `Link` (@kachar)
  > Combine interfaces of https://nextjs.org/docs/api-reference/next/link and https://material-ui.com/components/links/
- [x] `LinkButton` (@kachar)
  > Combine interfaces of https://nextjs.org/docs/api-reference/next/link and https://material-ui.com/components/buttons/
- [x] `GenericForm` (#8, thanks to @Nikola-Andreev)
  > Component to be used as base in order to allow easy replacement of underlying form library
- [x] `EmailSubscriptionForm`
  > Reusable email subscription form. Might be used in the footer or in the body
- [x] `LoginForm` (#12, thanks to @ani-kalpachka)
- [x] `RegisterForm` (#12, thanks to @ani-kalpachka)
- [x] `ResetEmailForm` (#12, thanks to @ani-kalpachka)
- [x] `ConfirmationDialog` (#17, thanks to @Nikola-Andreev)
  > Title, Description, Actions (Yes/No, Confirm/Cancel) https://material-ui.com/components/dialogs/#dialog

:information_source: Feel free to pick a component and extract the implementation in separate issue or PR.

**Comment by sotir-ls** [comment]
Have we got any designs (breakpoints) to work against?

**Comment by kachar** [comment]
@sotir-ls Not yet as far as I know

Anyhow the idea is to create the most common usecases for a web app - the must-haves

Feel free to extend the list in the issue description

**Comment by kachar** [comment]
Closing this one as all the points above are done :heavy_check_mark: 

Steady foundation for the app! Thanks to everyone involved in the process :100:
